CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "account_customer_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customer_id" integer NOT NULL REFERENCES "account_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "account_customer_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "customer_id" integer NOT NULL REFERENCES "account_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "account_address" ("id" char(32) NOT NULL PRIMARY KEY, "full_name" varchar(150) NOT NULL, "phone" varchar(50) NOT NULL, "postcode" varchar(50) NOT NULL, "address_line" varchar(255) NOT NULL, "address_line2" varchar(255) NOT NULL, "town_city" varchar(150) NOT NULL, "delivery_instructions" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "default" bool NOT NULL, "customer_id" integer NOT NULL REFERENCES "account_customer" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "account_customer_groups_customer_id_group_id_d501b316_uniq" ON "account_customer_groups" ("customer_id", "group_id");
CREATE INDEX "account_customer_groups_customer_id_a98350d1" ON "account_customer_groups" ("customer_id");
CREATE INDEX "account_customer_groups_group_id_c1cf6611" ON "account_customer_groups" ("group_id");
CREATE UNIQUE INDEX "account_customer_user_permissions_customer_id_permission_id_05910c6f_uniq" ON "account_customer_user_permissions" ("customer_id", "permission_id");
CREATE INDEX "account_customer_user_permissions_customer_id_0eddb67e" ON "account_customer_user_permissions" ("customer_id");
CREATE INDEX "account_customer_user_permissions_permission_id_508cbdb1" ON "account_customer_user_permissions" ("permission_id");
CREATE INDEX "account_address_customer_id_752e23ab" ON "account_address" ("customer_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "account_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "account_customer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "name" varchar(150) NOT NULL, "mobile" varchar(20) NOT NULL, "is_active" bool NOT NULL, "is_staff" bool NOT NULL, "created" datetime NOT NULL, "updated" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "checkout_deliveryoptions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "delivery_name" varchar(255) NOT NULL, "delivery_price" decimal NOT NULL, "delivery_method" varchar(255) NOT NULL, "delivery_timeframe" varchar(255) NOT NULL, "delivery_window" varchar(255) NOT NULL, "order" integer NOT NULL, "is_active" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "checkout_paymentselections" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "is_active" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "shop_producttype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL UNIQUE, "is_active" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "shop_productspecificationvalue" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "value" varchar(255) NOT NULL, "product_id" bigint NOT NULL REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED, "specification_id" bigint NOT NULL REFERENCES "shop_productspecification" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "shop_productspecification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "product_type_id" bigint NOT NULL REFERENCES "shop_producttype" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "shop_productspecificationvalue_product_id_028dfae8" ON "shop_productspecificationvalue" ("product_id");
CREATE INDEX "shop_productspecificationvalue_specification_id_9cdd636d" ON "shop_productspecificationvalue" ("specification_id");
CREATE INDEX "shop_productspecification_product_type_id_0d92fc74" ON "shop_productspecification" ("product_type_id");
CREATE TABLE IF NOT EXISTS "shop_productimage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NOT NULL, "alt_text" varchar(255) NULL, "is_feature" bool NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "product_id" bigint NOT NULL REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "shop_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "description" text NOT NULL, "slug" varchar(255) NOT NULL, "regular_price" decimal NOT NULL, "discount_price" decimal NOT NULL, "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "category_id" bigint NOT NULL REFERENCES "shop_category" ("id") DEFERRABLE INITIALLY DEFERRED, "product_type_id" bigint NOT NULL REFERENCES "shop_producttype" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "shop_productimage_product_id_65b3b20c" ON "shop_productimage" ("product_id");
CREATE INDEX "shop_product_slug_30bd2d5d" ON "shop_product" ("slug");
CREATE INDEX "shop_product_category_id_14d7eea8" ON "shop_product" ("category_id");
CREATE INDEX "shop_product_product_type_id_1a6738f6" ON "shop_product" ("product_type_id");
CREATE TABLE IF NOT EXISTS "shop_product_users_wishlist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "product_id" bigint NOT NULL REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED, "customer_id" bigint NOT NULL REFERENCES "account_customer" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "shop_product_users_wishlist_product_id_customer_id_c836f1d0_uniq" ON "shop_product_users_wishlist" ("product_id", "customer_id");
CREATE INDEX "shop_product_users_wishlist_product_id_f16937bc" ON "shop_product_users_wishlist" ("product_id");
CREATE INDEX "shop_product_users_wishlist_customer_id_6ebaf6db" ON "shop_product_users_wishlist" ("customer_id");
CREATE TABLE IF NOT EXISTS "orders_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "full_name" varchar(50) NOT NULL, "email" varchar(254) NOT NULL, "address1" varchar(250) NOT NULL, "address2" varchar(250) NOT NULL, "city" varchar(100) NOT NULL, "phone" varchar(100) NOT NULL, "postal_code" varchar(20) NOT NULL, "country_code" varchar(4) NOT NULL, "created" datetime NOT NULL, "updated" datetime NOT NULL, "total_paid" decimal NOT NULL, "order_key" varchar(200) NOT NULL, "payment_option" varchar(200) NOT NULL, "billing_status" bool NOT NULL, "user_id" bigint NOT NULL REFERENCES "account_customer" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "orders_orderitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "price" decimal NOT NULL, "quantity" integer unsigned NOT NULL CHECK ("quantity" >= 0), "order_id" bigint NOT NULL REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "orders_order_user_id_e9b59eb1" ON "orders_order" ("user_id");
CREATE INDEX "orders_orderitem_order_id_fe61a34d" ON "orders_orderitem" ("order_id");
CREATE INDEX "orders_orderitem_product_id_afe4254a" ON "orders_orderitem" ("product_id");
CREATE TABLE IF NOT EXISTS "shop_category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL UNIQUE, "slug" varchar(255) NOT NULL UNIQUE, "is_active" bool NOT NULL, "lft" integer unsigned NOT NULL CHECK ("lft" >= 0), "rght" integer unsigned NOT NULL CHECK ("rght" >= 0), "tree_id" integer unsigned NOT NULL CHECK ("tree_id" >= 0), "level" integer unsigned NOT NULL CHECK ("level" >= 0), "image" varchar(100) NOT NULL, "parent_id" bigint NULL REFERENCES "shop_category" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "shop_category_tree_id_c48d9e64" ON "shop_category" ("tree_id");
CREATE INDEX "shop_category_parent_id_901626c9" ON "shop_category" ("parent_id");
