# Generated by Django 4.2 on 2023-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="images/default.png",
                help_text="Upload a category image",
                upload_to="media/images",
                verbose_name="image",
            ),
        ),
    ]
