# Generated by Django 4.2 on 2023-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=255,
                unique=True,
                verbose_name="URL-friendly version of the category name",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "The price must be between 0 and 999.99."}
                },
                help_text="Maximum 999.99",
                max_digits=6,
                verbose_name="Discount price",
            ),
        ),
    ]
