# Generated by Django 4.2 on 2023-04-25 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="country_code",
        ),
    ]
